# Generated by Django 6.0.3 on 2026-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='notes',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='attempt_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
