# Generated by Django 6.0.3 on 2026-03-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_loginattempt_notes_loginattempt_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
