# Generated by Django 6.0.3 on 2026-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_loginattempt_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
